### ISSUE TITLE
background color functionality

### ISSUE THREAD

**Issue by Jayeshnangare** [Jayeshnangare/FlowMake#2]
after selecting colors background color of the shape should be changed

**Comment by tejas11054** [comment]
background color for all the shapes has to be same or each shape should have different color?

**Comment by Jayeshnangare** [comment]
Yes sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tejas11054** [comment]
Hello sir,
We have solved both issues listed by you along with that we have also made some UI Improvement (eg. your logo was not clearly visible in home page). So now can we make a combined pull request or do we have to make separate request for all 3 works?

**Comment by Jayeshnangare** [comment]
Include all work in single pull request and also add one file named as Contribution.md in that file you can explain all the work which you have done.

**Comment by Jayeshnangare** [comment]
Hi Tejas,

Thank you for solving our issues and suggesting us some additional improvements. We greatly appreciate your contribution. We have reviewed your solution and we will be adding that into our code.

Thank you!!
